title: Prefab Dependency Tracker
description: The ultimate tool for visualizing and managing prefab dependencies in Unity.
url: https://DecNet-Games.github.io
baseurl: "/PrefabDependency-Doc"

theme: just-the-docs

aux_links:
  "GitHub Repository":
    - //github.com/DecNet-Games/PrefabDependency-Doc

heading_anchors: true

# Color scheme
color_scheme: dark

# Footer
footer_content: "Copyright &copy; 2026 DecNet Games. All rights reserved."
